-- workers-oauth-provider PostgreSQL storage schema, version 1. Immutable after release.
CREATE TABLE oauth_clients (namespace text NOT NULL, client_id text NOT NULL, value jsonb NOT NULL, schema_version integer NOT NULL CHECK(schema_version>=0), revision bigint NOT NULL CHECK(revision>=0), created_at bigint NOT NULL CHECK(created_at>=0), expires_at bigint, PRIMARY KEY(namespace,client_id));
CREATE TABLE oauth_grants (namespace text NOT NULL, user_id text NOT NULL, grant_id text NOT NULL, client_id text NOT NULL, registered_client_id text, value jsonb NOT NULL, schema_version integer NOT NULL CHECK(schema_version>=0), revision bigint NOT NULL CHECK(revision>=0), created_at bigint NOT NULL CHECK(created_at>=0), expires_at bigint, transition_fence bigint NOT NULL DEFAULT 0 CHECK(transition_fence>=0), transition_lease_id text, transition_owner_id text, transition_kind text CHECK(transition_kind IN ('authorization_code','refresh_token')), transition_credential_id char(64), transition_callback_key char(64), transition_lease_expires_at bigint, PRIMARY KEY(namespace,user_id,grant_id), CHECK(registered_client_id IS NULL OR registered_client_id=client_id), FOREIGN KEY(namespace,registered_client_id) REFERENCES oauth_clients(namespace,client_id) ON DELETE CASCADE);
CREATE INDEX oauth_grants_client_idx ON oauth_grants(namespace,client_id,grant_id);
CREATE INDEX oauth_grants_user_client_idx ON oauth_grants(namespace,user_id,client_id);
CREATE TABLE oauth_access_tokens (namespace text NOT NULL, user_id text NOT NULL, grant_id text NOT NULL, token_id char(64) NOT NULL CHECK(token_id ~ '^[0-9a-f]{64}$'), value jsonb NOT NULL, schema_version integer NOT NULL CHECK(schema_version>=0), revision bigint NOT NULL CHECK(revision>=0), created_at bigint NOT NULL CHECK(created_at>=0), expires_at bigint NOT NULL, PRIMARY KEY(namespace,user_id,grant_id,token_id), FOREIGN KEY(namespace,user_id,grant_id) REFERENCES oauth_grants(namespace,user_id,grant_id) ON DELETE CASCADE);
CREATE INDEX oauth_access_tokens_expiry_idx ON oauth_access_tokens(namespace,expires_at);
CREATE TABLE oauth_consents (namespace text NOT NULL, user_id text NOT NULL, client_id text NOT NULL, reference_id text NOT NULL DEFAULT '', value jsonb NOT NULL, schema_version integer NOT NULL CHECK(schema_version>=0), revision bigint NOT NULL CHECK(revision>=0), created_at bigint NOT NULL CHECK(created_at>=0), expires_at bigint, PRIMARY KEY(namespace,user_id,client_id,reference_id));
CREATE INDEX oauth_consents_user_idx ON oauth_consents(namespace,user_id,client_id,reference_id);
CREATE TABLE oauth_replay_reservations (namespace text NOT NULL, reservation_namespace text NOT NULL, key_hash char(64) NOT NULL CHECK(key_hash ~ '^[0-9a-f]{64}$'), expires_at bigint NOT NULL, PRIMARY KEY(namespace,reservation_namespace,key_hash));
CREATE INDEX oauth_replay_expiry_idx ON oauth_replay_reservations(namespace,expires_at);
