import {
  assertInitialStorageRevision,
  assertNextStorageRevision,
  assertStoredAccessToken,
  assertStoredGrant,
  credentialIdFromSha256,
  type CredentialId,
  type GrantKey,
  type StoredAccessToken,
  type StoredGrant,
  type UnixSeconds,
} from './records';

/** Grant transition serialized by a lease. */
export type GrantTransitionKind = 'authorization_code' | 'refresh_token';

/** Opaque lease identifier generated by storage. */
export type TransitionLeaseId = string & { readonly __transitionLeaseId: unique symbol };

/** Unique identifier for one request attempting a transition. */
export type TransitionOwnerId = string & { readonly __transitionOwnerId: unique symbol };

/** Stable digest supplied to an application callback for safe retry support. */
export type CallbackIdempotencyKey = string & { readonly __callbackIdempotencyKey: unique symbol };

/**
 * Bounded cross-backend transition lease.
 *
 * A lease never represents an open SQL transaction or lock held across an
 * application callback. The monotonic fence rejects stale commit attempts.
 */
export interface GrantTransitionLease {
  readonly id: TransitionLeaseId;
  readonly grant: Readonly<GrantKey>;
  readonly kind: GrantTransitionKind;
  /** Hash of the code or refresh token authorized by this lease. */
  readonly credentialId: CredentialId;
  readonly ownerId: TransitionOwnerId;
  /** Monotonic token generated within the grant's serialization domain. */
  readonly fence: number;
  /** Grant revision that the final commit must replace. */
  readonly expectedRevision: number;
  /** Time after which this lease may not commit. */
  readonly expiresAt: UnixSeconds;
  /** Stable across retries of the same namespace/grant/kind/credential tuple. */
  readonly callbackIdempotencyKey: CallbackIdempotencyKey;
}

const BEGIN_INPUT_KIND: unique symbol = Symbol('OAuthBeginTransitionInput');
const COMMIT_INPUT_KIND: unique symbol = Symbol('OAuthCommitTransitionInput');

/** Validated input for acquiring authority over one code or refresh token. */
export type BeginGrantTransitionInput = Readonly<{
  readonly grant: Readonly<GrantKey>;
  readonly kind: GrantTransitionKind;
  /** Hash of the presented credential, never the raw credential. */
  readonly credentialId: CredentialId;
  readonly ownerId: TransitionOwnerId;
  readonly callbackIdempotencyKey: CallbackIdempotencyKey;
  readonly leaseTtlSeconds: number;
  readonly now: UnixSeconds;
}> & {
  readonly [BEGIN_INPUT_KIND]: true;
};

/** Asserts that input came from {@link beginGrantTransitionInput}. */
export function assertBeginGrantTransitionInput(value: unknown): asserts value is BeginGrantTransitionInput {
  if (
    typeof value !== 'object' ||
    value === null ||
    !(BEGIN_INPUT_KIND in value) ||
    (value as { readonly [BEGIN_INPUT_KIND]?: unknown })[BEGIN_INPUT_KIND] !== true
  ) {
    throw new TypeError('Expected validated begin-grant-transition input');
  }
}

/** Discriminated transition acquisition outcome. */
export type BeginGrantTransitionResult =
  | {
      readonly status: 'acquired';
      readonly grant: StoredGrant;
      readonly lease: GrantTransitionLease;
    }
  | { readonly status: 'busy'; readonly retryAfterSeconds: number }
  | { readonly status: 'invalid_credential' }
  | { readonly status: 'already_consumed' }
  | { readonly status: 'expired' }
  | { readonly status: 'not_found' };

/** Validated complete local state supplied only after an application callback returns. */
export type ValidatedCommitGrantTransitionInput = Readonly<{
  readonly lease: GrantTransitionLease;
  readonly now: UnixSeconds;
  /** Complete immediate successor of the leased grant revision. */
  readonly grant: StoredGrant;
  /** New access token created atomically with the next grant revision. */
  readonly accessToken: StoredAccessToken;
}> & {
  readonly [COMMIT_INPUT_KIND]: true;
};

/** Asserts that input came from {@link commitGrantTransitionInput}. */
export function assertCommitGrantTransitionInput(value: unknown): asserts value is ValidatedCommitGrantTransitionInput {
  if (
    typeof value !== 'object' ||
    value === null ||
    !(COMMIT_INPUT_KIND in value) ||
    (value as { readonly [COMMIT_INPUT_KIND]?: unknown })[COMMIT_INPUT_KIND] !== true
  ) {
    throw new TypeError('Expected validated commit-grant-transition input');
  }
}

/** Discriminated transition commit outcome. */
export type CommitGrantTransitionResult =
  | { readonly status: 'committed' }
  | { readonly status: 'lease_lost' }
  | { readonly status: 'conflict' }
  | { readonly status: 'expired' }
  | { readonly status: 'not_found' };

/** Input for releasing a still-matching transition lease. */
export interface AbortGrantTransitionInput {
  readonly lease: GrantTransitionLease;
  readonly now: UnixSeconds;
}

/** Discriminated transition abort outcome. */
export type AbortGrantTransitionResult =
  | { readonly status: 'aborted' }
  | { readonly status: 'lease_lost' }
  | { readonly status: 'not_found' };

/** Creates a branded lease identifier from a bounded adapter-generated value. */
export function transitionLeaseId(value: string): TransitionLeaseId {
  assertOpaqueIdentifier(value, 'Transition lease ID');
  return value as TransitionLeaseId;
}

/** Creates a branded transition owner identifier from a bounded random value. */
export function transitionOwnerId(value: string): TransitionOwnerId {
  assertOpaqueIdentifier(value, 'Transition owner ID');
  return value as TransitionOwnerId;
}

/** Creates a callback idempotency key from a lowercase SHA-256 digest. */
export function callbackIdempotencyKey(value: string): CallbackIdempotencyKey {
  if (!/^[0-9a-f]{64}$/.test(value)) {
    throw new TypeError('Callback idempotency key must be a lowercase SHA-256 digest');
  }
  return value as CallbackIdempotencyKey;
}

/**
 * Derives the callback key from every field defining one credential attempt.
 * Different lease owners and fences deliberately do not change the result.
 */
export async function deriveCallbackIdempotencyKey(input: {
  readonly namespace: string;
  readonly grant: GrantKey;
  readonly kind: GrantTransitionKind;
  readonly credentialId: CredentialId;
}): Promise<CallbackIdempotencyKey> {
  if (input.namespace.length === 0) throw new TypeError('Storage namespace must not be empty');
  assertGrantKey(input.grant);
  assertTransitionKind(input.kind);
  credentialIdFromSha256(input.credentialId);
  const encoded = new TextEncoder().encode(
    JSON.stringify([input.namespace, input.grant.userId, input.grant.grantId, input.kind, input.credentialId])
  );
  const digest = await crypto.subtle.digest('SHA-256', encoded);
  return callbackIdempotencyKey(
    Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('')
  );
}

/** Creates validated begin input with a deterministic callback idempotency key. */
export async function beginGrantTransitionInput(input: {
  readonly namespace: string;
  readonly grant: GrantKey;
  readonly kind: GrantTransitionKind;
  readonly credentialId: CredentialId;
  readonly ownerId: TransitionOwnerId;
  readonly leaseTtlSeconds: number;
  readonly now: UnixSeconds;
}): Promise<BeginGrantTransitionInput> {
  assertGrantKey(input.grant);
  assertTransitionKind(input.kind);
  credentialIdFromSha256(input.credentialId);
  assertUnixSeconds(input.now, 'now');
  if (!Number.isSafeInteger(input.leaseTtlSeconds) || input.leaseTtlSeconds < 1) {
    throw new TypeError('leaseTtlSeconds must be a positive safe integer');
  }
  const callbackKey = await deriveCallbackIdempotencyKey(input);
  return Object.freeze(
    Object.defineProperty(
      {
        grant: Object.freeze({ ...input.grant }),
        kind: input.kind,
        credentialId: input.credentialId,
        ownerId: input.ownerId,
        callbackIdempotencyKey: callbackKey,
        leaseTtlSeconds: input.leaseTtlSeconds,
        now: input.now,
      },
      BEGIN_INPUT_KIND,
      { value: true, enumerable: false }
    )
  ) as BeginGrantTransitionInput;
}

/** Validates an adapter's acquired lease against the authoritative begin input. */
export function validateBeginGrantTransitionResult(
  input: BeginGrantTransitionInput,
  result: BeginGrantTransitionResult,
  maximumTtlSeconds: number
): BeginGrantTransitionResult {
  if (result.status !== 'acquired') {
    if (result.status === 'busy' && (!Number.isSafeInteger(result.retryAfterSeconds) || result.retryAfterSeconds < 1)) {
      throw new TypeError('Busy transition result requires a positive retry delay');
    }
    return result;
  }

  assertStoredGrant(result.grant);
  const lease = createGrantTransitionLease(result.lease, input.now, maximumTtlSeconds);
  if (
    lease.grant.userId !== input.grant.userId ||
    lease.grant.grantId !== input.grant.grantId ||
    lease.kind !== input.kind ||
    lease.credentialId !== input.credentialId ||
    lease.ownerId !== input.ownerId ||
    lease.callbackIdempotencyKey !== input.callbackIdempotencyKey ||
    lease.expectedRevision !== result.grant.metadata.revision
  ) {
    throw new TypeError('Acquired transition lease does not match the begin input and grant');
  }
  if (result.grant.value.userId !== input.grant.userId || result.grant.value.id !== input.grant.grantId) {
    throw new TypeError('Acquired transition grant does not match the requested grant');
  }
  return Object.freeze({ ...result, lease });
}

/** Creates a validated transition commit plan bound to the leased aggregate. */
export function commitGrantTransitionInput(input: {
  readonly lease: GrantTransitionLease;
  readonly now: UnixSeconds;
  readonly grant: StoredGrant;
  readonly accessToken: StoredAccessToken;
}): ValidatedCommitGrantTransitionInput {
  assertStoredGrant(input.grant);
  assertStoredAccessToken(input.accessToken);
  assertUnixSeconds(input.now, 'now');
  if (input.now >= input.lease.expiresAt) throw new TypeError('Transition lease has expired');
  assertNextStorageRevision(input.lease.expectedRevision, input.grant);
  assertInitialStorageRevision(input.accessToken);
  if (!input.accessToken.value.grant) {
    throw new TypeError('Transition access token must include grant metadata');
  }
  if (
    input.grant.value.userId !== input.lease.grant.userId ||
    input.grant.value.id !== input.lease.grant.grantId ||
    input.accessToken.value.userId !== input.lease.grant.userId ||
    input.accessToken.value.grantId !== input.lease.grant.grantId ||
    input.accessToken.value.grant.clientId !== input.grant.value.clientId
  ) {
    throw new TypeError('Transition grant and access token must belong to the leased aggregate');
  }

  return Object.freeze(
    Object.defineProperty({ ...input }, COMMIT_INPUT_KIND, {
      value: true,
      enumerable: false,
    })
  ) as ValidatedCommitGrantTransitionInput;
}

/** Validates lease invariants and returns a frozen copy. */
export function createGrantTransitionLease(
  input: GrantTransitionLease,
  now: UnixSeconds,
  maximumTtlSeconds: number
): GrantTransitionLease {
  assertUnixSeconds(now, 'now');
  if (!Number.isSafeInteger(maximumTtlSeconds) || maximumTtlSeconds < 1) {
    throw new TypeError('maximumTtlSeconds must be a positive safe integer');
  }
  transitionLeaseId(input.id);
  transitionOwnerId(input.ownerId);
  callbackIdempotencyKey(input.callbackIdempotencyKey);
  assertGrantKey(input.grant);
  assertTransitionKind(input.kind);
  credentialIdFromSha256(input.credentialId);
  if (!Number.isSafeInteger(input.fence) || input.fence < 1) {
    throw new TypeError('Transition fence must be a positive safe integer');
  }
  if (!Number.isSafeInteger(input.expectedRevision) || input.expectedRevision < 0) {
    throw new TypeError('Expected revision must be a non-negative safe integer');
  }
  if (!Number.isSafeInteger(input.expiresAt) || input.expiresAt <= now) {
    throw new TypeError('Transition lease must expire in the future');
  }
  if (input.expiresAt - now > maximumTtlSeconds) {
    throw new TypeError('Transition lease exceeds the configured maximum lifetime');
  }

  return Object.freeze({ ...input, grant: Object.freeze({ ...input.grant }) });
}

function assertOpaqueIdentifier(value: string, name: string): void {
  if (value.length < 1 || value.length > 128 || /[\u0000-\u001f\u007f]/.test(value) || value.trim() !== value) {
    throw new TypeError(`${name} must be a bounded opaque identifier without control or surrounding whitespace`);
  }
}

function assertGrantKey(value: GrantKey): void {
  if (value.userId.length === 0 || value.grantId.length === 0) {
    throw new TypeError('Transition grant key must not be empty');
  }
}

function assertTransitionKind(value: GrantTransitionKind): void {
  if (value !== 'authorization_code' && value !== 'refresh_token') {
    throw new TypeError('Invalid transition kind');
  }
}

function assertUnixSeconds(value: number, name: string): void {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new TypeError(`${name} must be a non-negative Unix timestamp in whole seconds`);
  }
}
