name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'cloudflare' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Modify package.json version
        run: npx tsx .github/version-script.ts

      - run: npm run build
      - run: npm run check

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

